[template]
prefix = "/wodby/actions/$WODBY_NAMESPACE/web-backend/app"
src = "app_migrate.tmpl"
dest = "/opt/wodby/actions/actions.d/app_migrate.json"
uid = 0
gid = 0
mode = "0600"
keys = [
  "/migrate",
]
reload_cmd = "/opt/wodby/actions/app/migrate/run"