[template]
prefix = "/wodby/actions/$WODBY_NAMESPACE/web-backend/app"
src = "app_update.tmpl"
dest = "/opt/wodby/actions/actions.d/app_update.json"
uid = 0
gid = 0
mode = "0600"
keys = [
  "/update",
]
reload_cmd = "/opt/wodby/actions/app/update/run"