[template]
prefix = "/wodby/states/execute/$WODBY_NAMESPACE/web-backend"
src = "app_init.tmpl"
dest = "/etc/wodby/app_init"
uid = 0
gid = 0
mode = "0600"
keys = [
  "/init",
]
reload_cmd = "/opt/bin/app_init"