[template]
prefix = "/wodby/states/execute/$WODBY_NAMESPACE/web-backend"
src = "backup_ctl.tmpl"
dest = "/etc/wodby/backup_ctl"
uid = 0
gid = 0
mode = "0600"
keys = [
  "/backup_ctl",
]
reload_cmd = "/opt/bin/backup_ctl"