[template]
prefix = "/wodby/states/execute/$WODBY_NAMESPACE/web-backend"
src = "cache_php.tmpl"
dest = "/etc/wodby/cache_php.env"
uid = 0
gid = 0
mode = "0600"
keys = [
  "/cache_php",
]
reload_cmd = "/opt/bin/wodby_cache_php"