[template]
prefix = "/wodby/states/execute/$WODBY_NAMESPACE/web-backend"
src = "git_commit.tmpl"
dest = "/etc/wodby/git_commit.env"
uid = 0
gid = 0
mode = "0600"
keys = [
  "/git_commit",
]
reload_cmd = "/opt/bin/wodby_git_commit"