[template]
prefix = "/wodby/states/execute/$WODBY_NAMESPACE/web-backend"
src = "git_url.tmpl"
dest = "/etc/wodby/git_url.env"
uid = 0
gid = 0
mode = "0600"
keys = [
  "/git_url",
]
reload_cmd = "/opt/bin/wodby_git_clone"