[template]
prefix = "/wodby/states/execute/$WODBY_NAMESPACE/web-backend"
src = "git_branch.tmpl"
dest = "/etc/wodby/git_branch.env"
uid = 0
gid = 0
mode = "0600"
keys = [
  "/git_branch",
]
reload_cmd = "/opt/bin/wodby_git_checkout"