[template]
prefix = "/wodby/states/execute/$WODBY_NAMESPACE/web-backend"
src = "git_ctl.tmpl"
dest = "/etc/wodby/git_ctl"
uid = 0
gid = 0
mode = "0600"
keys = [
  "/git_ctl",
]
reload_cmd = "/opt/bin/git_ctl"