[template]
prefix = "/wodby/states/execute/$WODBY_NAMESPACE/web-backend"
src = "wodby_diff_repo.tmpl"
dest = "/etc/wodby/diff_repo.env"
uid = 0
gid = 0
mode = "0600"
keys = [
  "/diff_repo",
]
reload_cmd = "/opt/bin/wodby_diff_repo"