[template]
prefix = "/wodby/states/execute/$WODBY_NAMESPACE/web-backend"
src = "wodby_diff_file.tmpl"
dest = "/etc/wodby/diff_file.env"
uid = 0
gid = 0
mode = "0600"
keys = [
  "/diff_file",
]
reload_cmd = "/opt/bin/wodby_diff_file"